import { ReactQueryProvider } from '@/utils/react-query-provider.utilt';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ProfileContextProvider } from '@/context/profile.context';
import StyledComponentsRegistry from '@/utils/styled-components-registry';
import { VisitorContextProvider } from '@/context/visitor.context';
import { NavBar } from '@/components/navBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ProfileContextProvider>
          <StyledComponentsRegistry>
            <VisitorContextProvider>
              <body className={inter.className}>
                {
                  <>
                    <NavBar />
                    {children}
                  </>
                }
              </body>
            </VisitorContextProvider>
          </StyledComponentsRegistry>
        </ProfileContextProvider>
      </ReactQueryProvider>
    </html>
  );
}
