import { ReactQueryProvider } from '@/utils/react-query-provider.utilt';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../../utils/styled-components-registry';
import { ProfileContextProvider } from '../../context/profile.context';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ProfileContextProvider>
          <StyledComponentsRegistry>
            <body className={inter.className}>{children}</body>
          </StyledComponentsRegistry>
        </ProfileContextProvider>
      </ReactQueryProvider>
    </html>
  );
}
